VERSION="2.2.1"

ACCOUNTS=[
"GADJRWBZWBZCIYFIG2NNQQMOSFKUWA4GDXO3HFKNK6IKFMZYXEJKRNEO",
]

[DOCUMENTATION]
ORG_NAME="Blum"
ORG_URL="https://www.blum-stellar.com/"
ORG_DESCRIPTION="At Blum, we believe in making your crypto journey not just profitable, but also enjoyable and interactive"
ORG_LOGO="https://www.blum-stellar.com/blum.png"


[[CURRENCIES]]
code="Blum"
status="live"
display_decimals=3
issuer="GADJRWBZWBZCIYFIG2NNQQMOSFKUWA4GDXO3HFKNK6IKFMZYXEJKRNEO"
anchor_asset_type="crypto"
name="Blum"
desc="At Blum, we believe in making your crypto journey not just profitable, but also enjoyable and interactive"
image="https://www.blum-stellar.com/blum.png"
